name: publish OllieBear.Infrastructure.Serialization to nuget

on:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'src/Infrastructure.Serialization/**'
jobs:
  build:
    name: list OllieBear.Infrastructure.Serialization on nuget.org
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore OllieBear.Infrastructure.Serialization project dependencies
      run: dotnet restore src/Infrastructure.Serialization/Infrastructure.Serialization.csproj
    - name: Build OllieBear.Infrastructure.Serialization project
      run: dotnet build src/Infrastructure.Serialization/Infrastructure.Serialization.csproj --no-restore --configuration Release
    - name: Pack OllieBear.Infrastructure.Serialization project
      run: dotnet pack src/Infrastructure.Serialization/Infrastructure.Serialization.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
    - name: Publish OllieBear.Infrastructure.Serialization package to NuGet
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
